### ISSUE TITLE
相同主板，引导进入跑码后黑屏

### ISSUE THREAD

**Issue by superyzr** [NEEPUCS/Ausu-ROG-Strix-B360i-HACKINTOSH-OPENCORE-EFI#1]
感谢提供EFI👍

主板:华硕B360i
显卡:蓝宝石RX5500XT超白金
CPU: i5-9400F（无核显）
已添加三码，开机引导能显示系统选择图标，可以正常选择进入win10,但是选择进入苹果系统(big sur 11.1)跑码后就黑屏了，我使用这份EFI替换了原本的EFI（我自己的EFI无法引导win10😭）
请问是有其它配置原因吗？（已按README提示修改了相关配置）

**Comment by NEEPUCS** [comment]
最近没有时间 明天回复您
如果您着急，可以加Q群1125705781（不是推广，我也不是管理），里面会有人也遇见此问题并解答您的疑惑

**Comment by NEEPUCS** [comment]
说两句 boot-args 加agdpmod=pikera 启动参数了吗？
